### ISSUE TITLE
Development of an application using excel for design of a double rotor axial flux motor

### ISSUE THREAD

**Issue by 12Tall** [12Tall/youtube_dl_actions#7]
https://www.youtube.com/watch?v=-LM2Bx0HGkQ

**Comment by aergun** [comment]
Can you upload the excel file again? Thanks

**Comment by 12Tall** [comment]
Welcome to use tmp.link upload service.
Upload Complete.
Download Page: https://ttttt.link/f/66557455961db
Thank you for using our services.
password:`1963678409`

**Comment by aergun** [comment]
Can you upload the excel file again? Thanks

**Comment by 12Tall** [comment]
> Can you upload the excel file again? Thanks

Sorry, I can't Access the Excel file, this repo is build for video saving only.  you can visit <https://www.comprogexpert.com> to download :)

**Comment by 12Tall** [comment]
Welcome to use tmp.link upload service.
Upload Complete.
Download Page: https://ttttt.link/f/6656c9eebfea2
Thank you for using our services.
  password:`1963678409`

**Comment by 12Tall** [comment]
Auto-closing issue
